model_list:
- model_name: uac-default
  litellm_params:
    model: openrouter/z-ai/glm-5.3
- model_name: uac-default-moonshotai--kimi-k2.7-code
  litellm_params:
    model: openrouter/moonshotai/kimi-k2.7-code
- model_name: uac-default-poolside--laguna-s-2.1
  litellm_params:
    model: openrouter/poolside/laguna-s-2.1
- model_name: uac-background
  litellm_params:
    model: openrouter/poolside/laguna-s-2.1
- model_name: uac-background-deepseek--deepseek-v4-flash-0731
  litellm_params:
    model: openrouter/deepseek/deepseek-v4-flash-0731
- model_name: uac-background-google--gemini-3.7-flash
  litellm_params:
    model: openrouter/google/gemini-3.7-flash
- model_name: uac-reasoning
  litellm_params:
    model: openrouter/deepseek/deepseek-v4-pro-0813
- model_name: uac-vision
  litellm_params:
    model: openrouter/google/gemini-3.7-flash
litellm_settings:
  num_retries: 5
  request_timeout: 300
router_settings:
  fallbacks:
  - uac-default:
    - uac-default-moonshotai--kimi-k2.7-code
    - uac-default-poolside--laguna-s-2.1
  - uac-background:
    - uac-background-deepseek--deepseek-v4-flash-0731
    - uac-background-google--gemini-3.7-flash
